[Miraikan-611] Request user info when attend mode has been connected to the suitcase
CMU-cabot/cabot-ios-app pull request #13
Opened 2024-06-07 03:51 UTC by SeitaKayukawa

Related Issue:
https://github.com/miraikan-research/TODO/issues/611

2024-06-11 04:19 UTC, SeitaKayukawa commented
@miyazakifuki 
### これまでの問題
- ユーザアプリの状態（現在の目的地や設定されているツアー情報）はユーザアプリ上で状態のアップデートが起こった時のみアテンドアプリに反映される
- その結果，ユーザアプリで目的地を設定後にアテンドアプリを立ち上げると最初は設定された目的地情報がアテンドアプリから確認できない問題がある（アテンドアプリが途中で落ちて再立ち上げした際も同様）

### 修正内容
- アテンドアプリがスーツケースと接続された際に，ユーザアプリの状態をリクエストできるように
- ユーザアプリ上で何かしら目的地が設定されている場合にアテンドアプリへその情報が共有されアテンドアプリ上で確認できる

### テストしていただきたい内容
1. ユーザアプリで目的地/ツアーを設定→アテンドアプリを立ち上げ，スーツケースと接続→ユーザアプリ上で設定された目的地/ツアーをアテンドアプリから確認できるかチェック
2. ユーザアプリでツアーを設定→アテンドアプリ接続→ツアー実行→ツアー途中でアテンドアプリを落とす→アテンドアプリ立ち上げ，スーツケースと接続→設定されている目的地をアテンドアプリから確認できるかチェック
3. 2のチェックをユーザアプリ上でコンテンツ読み上げがされている時にも正常に動くかチェック（読み上げ内容の共有は行わないので目的地に関する情報のみがユーザアプリ - アテンドアプリ間でシェアされます）

2024-06-11 11:17 UTC, miyazakifuki commented
テスト1,2,3すべて期待通りの動作でした。

コードのレビューお願いします。 @dsato80

2024-06-11 12:39 UTC, daisukes requested changes
挙動は良いみたいですが、少し修正お願いします。

2024-06-11 12:39 UTC, daisukes commented on CaBot/CaBotAppModel.swift
> +                self.share(user_info: SharedInfo(type: .RequestUserInfo, value: ""))
これを送信するのはself.suitcaseConnected == trueの時だけで良いのでは？
ちょっと下にself.suitcaseConnectedをチェックしているところに入れては？

2024-06-11 12:39 UTC, daisukes commented on CaBot/CaBotAppModel.swift
> +        self.share(user_info: SharedInfo(type: .Tour, value: self.tourManager.title.text))
インデントが揃っていない？

2024-06-12 01:05 UTC, SeitaKayukawa commented
佐藤さんありがとうございます．
指摘していただいた点，修正してPushしました（動作も一通り確認済みです）

2024-06-12 02:13 UTC, daisukes approved these changes
LGTM

2024-06-12 02:13 UTC, merged