[Conso-245] clear destinations from Advanced mode
CMU-cabot/cabot-ios-app pull request #14
Opened 2024-06-13 01:59 UTC by SeitaKayukawa

- [ツアーの自動テスト実装](https://github.com/CMU-cabot/TODO-Consortium/issues/245)に伴い，ユーザモード上で設定された目的地をアテンドモードからクリアできるようにする機能が必要になったため実装
- アプリのUI上でクリアできるようにするにはViewの変更が伴うため含まれていないです
  - これについては急を要するアップデート内容ではないため，下記のissueを立てた上で[アプリ開発フェーズ1](https://github.com/CMU-cabot/TODO-Consortium/issues/244)に含め，ユーザ/アテンドアプリ分割後にPQさんのどなたかに実装してもらう予定です
  - https://github.com/CMU-cabot/TODO-Consortium/issues/349
  - @daisukes このような方針で問題ないでしょうか？

2024-06-13 02:03 UTC, daisukes commented
クリアした時に喋るのも止めた方が良い？
長いのを喋っている最中だとダラダラと喋り続ける気がしますが、どうでしょう？

2024-06-13 02:24 UTC, SeitaKayukawa commented
確かにクリアされた際に喋っている情報は必要のない情報なので喋るのも止めてよさそうですね

（ちなみに本件の主題とはズレますが，アプリのテスト時も"app speech completed"は待たずに"app speech speaking"のトピックが来ているかを見れば十分なのでは？（長い文章を喋り終わるまで待つのはテストに時間がかかる）とも思ってます）

実装としては[tourManagaer.clearAll()](https://github.com/CMU-cabot/cabot-ios-app/blob/2b29849314f39da5852612390e68f22b358b4a1b/CaBot/TourManager.swift#L146-L153)の中で今喋っている内容も全てクリアするイメージでしょうか？

（喋らせる実装まわりは詳しくないので「喋っている内容を全てクリアする」の具体的な実装は検討がついていないですが...）

2024-06-13 02:40 UTC, daisukes commented
https://github.com/CMU-cabot/cabot-ios-app/blob/2b29849314f39da5852612390e68f22b358b4a1b/CaBot/CaBotAppModel.swift#L901-L903

stopSpeakで止まるはず。

2024-06-13 03:16 UTC, SeitaKayukawa commented
クリア時に読み上げを止めるためにコードアップデートしました．

[`.ClearDestinations`を受け取った際](https://github.com/CMU-cabot/cabot-ios-app/blob/7d95efdcc54238598d7175668467697412e85cb1/CaBot/CaBotAppModel.swift#L1363)にstopSpeak()を呼ぶことも考えましたが，それだとアテンドアプリから目的地クリアした時のみ読み上げが停止され，ユーザアプリ上で目的地クリアした際にも読み上げが停止されないため，[clearAll()内でstopSpeak()を読んでいます](https://github.com/CMU-cabot/cabot-ios-app/blob/7d95efdcc54238598d7175668467697412e85cb1/CaBot/TourManager.swift#L152)

2024-06-13 03:32 UTC, daisukes requested changes
修正お願いします

2024-06-13 03:32 UTC, daisukes commented on CaBot/TourManager.swift
> +    func stopSpeak(manager: TourManager)
TourManagerがspeakに干渉するのは良くない気がします。
clearAllを呼んでいるところでstopSpeakするのが良いと思います。
コードが重複するのを避けるのであればModelの中に適当な関数を作って、それを呼ぶようにするのが良いと思います。

2024-06-14 02:28 UTC, SeitaKayukawa commented
修正しました．

以前のcommitでは.viewファイルの修正を避ける（ユーザ/アテンドアプリの分離をしているbranchとのマージが面倒になる）意図でtourManagerの中でstopSpeakを呼ぶようにしていましたが，clearAll()を読んでいるところでstopSpeakを呼ぶにせよ，Model内に適当な関数を作るにせよ，.viewファイルの修正は避けられませんでした．

確認お願いします．

（これがマージされた場合，PQの人たちにviewに修正が入ったのでマージお願いします．と連絡したほうが良いでしょうか？）

2024-06-14 02:37 UTC, daisukes approved these changes
LGTM

2024-06-14 02:39 UTC, merged

2024-06-14 02:40 UTC, daisukes commented
分割版へのマージは @SeitaKayukawa さんの方でやってもらうのが早いと思いますが、いかがでしょうか？
mainはリネームして開発を止めるので今後はexpo2025ブランチに入れるようにお願いします。

2024-06-14 03:10 UTC, SeitaKayukawa commented
mainをexpo2025へマージしました．

今後の開発はexpo2025ブランチに入れるとのことで承知しました．