testflight fix
CMU-cabot/cabot-ios-app pull request #15
Opened 2024-06-14 12:24 UTC by pq-ishida

**内容**
こちらのissueのコメントでも報告しましたがTestflightにアップロードする際に2つのエラーが発生しましたのでその修正と、未来館様Testfligthに合わせたプロファイルの変更が含まれたプルリクエストになります。

**報告したissue**
https://github.com/CMU-cabot/TODO-Consortium/issues/271#issuecomment-2154105314

**発生したエラーと解決方法**
```
Invalid bundle. Because your app supports Multitasking on iPad, you need to include the LaunchScreen launch storyboard file in your CMU.CaBotRemote.CaBot.Test bundle. Use UILaunchScreen instead if the app’s MinimumOSVersion is 14 or higher and you prefer to configure the launch screen without storyboards. For details, see: https://developer.apple.com/documentation/bundleresources/information_property_list/uilaunchstoryboardname (ID: dbe906df-c42d-4591-b72b-c273317549c2)
```
CaBot/Info.plistにUILaunchScreenKeyを追加いたしました。

```
ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “CaBot.app” bundle should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
```
CaBot/Info.plist、CaBot/en.lproj/InfoPlist.strings、CaBot/ja.lproj/InfoPlist.stringsにNSCameraUsageDescriptionKeyを追加いたしました。

ご確認よろしくお願いいたします。

2024-06-14 12:35 UTC, dsato80 requested changes
ありがとうございます。
基本良いのですが、チームやdistribution関係のところは空のままにしておいてください。

よろしくお願いします

2024-06-14 12:35 UTC, dsato80 commented on CaBot.xcodeproj/project.pbxproj
> +				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = H84S8WFTWG;
チームはコミットしないようにお願いします

2024-06-14 12:35 UTC, dsato80 commented on CaBot.xcodeproj/project.pbxproj
> +				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = H84S8WFTWG;
同じく

2024-06-14 12:35 UTC, dsato80 commented on CaBot.xcodeproj/project.pbxproj
> +				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "Cabot Test Distribution";
これも除いてくだい

2024-06-14 12:35 UTC, dsato80 commented on CaBot.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Distribution";
こちらも

2024-06-14 12:35 UTC, dsato80 commented on CaBot.xcodeproj/project.pbxproj
> +				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "Cabot Test Distribution";
これも

2024-06-14 12:45 UTC, pq-ishida commented
@dsato80 
失礼いたしました。
修正いたしましたので再度ご確認いただけますでしょうか。

2024-06-25 08:46 UTC, pq-ishida commented
@daisukes 
こちら問題なければmainにもマージいただけますでしょうか？
よろしくお願いいたします。

2024-06-25 11:02 UTC, dsato80 approved these changes
遅くなってすいません。

2024-06-25 11:03 UTC, merged