Pq chinka/resource download
CMU-cabot/cabot-ios-app pull request #20
Opened 2024-07-05 02:48 UTC by chenjia1988

タスク＃250（アプリのデータ読み込みをオンラインリソースを前提としたものに書き換える）が実装しました。
アプリ起動時にハッシュ値とリソースをzipしたファイルをMapServiceからダウンロードして、アプリのDocumentディレクトリに展開するのが実装しました。再度ダウンロードする前にハッシュ値を比較してから、ハッシュ値が同じであれば、ダウンロードせず、逆にダウンロードが行います。
サーバーへアクセスできない異常系でメインメニュー画面の上にエラーメッセージとリトライボタンが表示される。リトライボタンを押して、再度サーバーへサクセスを試すことができます。
以上の機能が実装しましたので、お手数ですが、ご確認のほど宜しくお願い致します。

2024-07-06 02:03 UTC, daisukes requested changes
PRありがとうございます。
ZIPをダウンロードしてリソースとして選択できるという基本的な流れは良いと思います。

## コードの修正

- コメントは英語でお願いします
- プログラム中に日本語は使わないようにお願いします。
- 日本語はLocalizable.stringsに入れてください
- XCodeでコードをフォーマットしてください

## ユーザビリティの観点で

- リソースがない状態だと言語が設定しておらず表示がおかしくなるので直したいです
- 最初、リソースがない状態ではリソース選択画面を出さずにメインメニューに直接飛ばしたいです
- リソース読み込みエラーのメッセージはheaderではなく、通常の文字サイズで表示してください
- headerにはリソースダウンロード（Resource Download）と表示してください

2024-07-06 05:10 UTC, chenjia1988 commented
ご確認いただきありがとうございます。
上記の指摘したところに関して、全て対応していたので、週明けに再度テストを行ってから、プッシュさせていただきます。

但し、一点仕様に関する確認したいことがあります。
Settingボタンを押して、設定画面で「Select Resource」ボタンを押して、ResourceSelectViewが表示される。
この画面でリソースデータのない状態であれば、何も表示されないので、メインメニュー画面へ戻れない。
上記の場合はリソースデータがなければ、ResourceSelectViewでReturn Mainmenuボタンを追加して、ボタンでMainmenuへ戻るように実装した。但し、このように実装すればよろしいでしょうか？(下記画像ようなイメージ）
<img width="405" alt="スクリーンショット 2024-07-06 13 45 46" src="https://github.com/CMU-cabot/cabot-ios-app/assets/23738812/ccc00182-8968-4454-b156-afd1c51dc1d0">

2024-07-06 12:00 UTC, dsato80 commented
- ダウンロードが成功したら自動的に選択する
- とすれば、リソース選択画面は不用になりそうです

2024-07-06 17:32 UTC, daisukes requested changes
まだ修正途中と思いますが、気になった点をコメントしました。

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +        let task = URLSession.shared.dataTask(with: md5FileURL!) { (data, response, error) in
force unwrap (!) は使わないようにお願いします。
md5FileURLはnilになる可能性があります（`appMode.primaryAddr`が間違っているような時）

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +        let downloadURL = URL(string: (path))!
force unwrapは使わないでください
それ以降の処理をせずに終了して良い場合には`guard let`、そうでない場合は`if let`を使ってください

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +        let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
同様

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +            print("Saving of Hash file is completed:\(fileURL.path)")
ログは`print`ではなく`NSLog`を使うように変更してください

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +                if let content = String(data: data, encoding: .utf8) {
`else`や、後続の処理がない場合にはguardを使った方が構造がネストしないのですっきりします

2024-07-06 17:32 UTC, daisukes commented on CaBot/ResourceDownload.swift
> +                        if components.count == 1
こちらもguardにする

2024-07-07 03:41 UTC, chenjia1988 commented on CaBot/ResourceDownload.swift
> +        let task = URLSession.shared.dataTask(with: md5FileURL!) { (data, response, error) in
ご確認いただきありがとうございます。
appModel.primaryAddrはnilや空配列になる可能性があります。なので、appModel.primaryAddrの判定処理が追加しました。
また、md5FileURLもif letにしました

2024-07-07 03:42 UTC, chenjia1988 commented on CaBot/ResourceDownload.swift
> +        let downloadURL = URL(string: (path))!
上記同様
appModel.primaryAddrの判定処理が追加しました。
downloadURLもif letにしました

2024-07-25 17:25 UTC, daisukes commented
修正ありがとうございます。最後細かいところはこちらで修正しました。
こちらのPRは運用の都合上、マージは一旦保留にさせてください。

2024-08-06 21:37 UTC, merged