make log time from log name and nanoseconds
CMU-cabot/cabot-ios-app pull request #8
Opened 2024-05-16 07:52 UTC by miyazakifuki

2024-05-16 22:23 UTC, dsato80 requested changes
日本語をコードに直接入れないようにお願いします。

2024-05-20 03:02 UTC, miyazakifuki commented
Viewにてアプリで設定されている言語はどのように取得したら良いですか？

2024-05-20 03:32 UTC, daisukes commented
`LocalizedStringKey`を使ってテキストを取得してください。
それぞれの言語のテキストは`Loclizable.strings`に設定します。

https://github.com/CMU-cabot/cabot-ios-app/blob/9eabdcb435811bb81000bd52d967926b4c800d95/CaBot/Views/MainMenuView.swift#L452

https://github.com/CMU-cabot/cabot-ios-app/blob/9eabdcb435811bb81000bd52d967926b4c800d95/CaBot/en.lproj/Localizable.strings#L128

https://github.com/CMU-cabot/cabot-ios-app/blob/9eabdcb435811bb81000bd52d967926b4c800d95/CaBot/ja.lproj/Localizable.strings#L128

2024-05-20 03:54 UTC, miyazakifuki commented
> LocalizedStringKeyを使ってテキストを取得してください。

すみません。ViewではなくCabotServiceCommonでした。
`timeOnlyFormatter.dateFormat = "HH'時'mm'分'ss'秒'"`
のようなformatの設定では言語に合わせて場合わけする必要がありそうです。

2024-05-20 04:02 UTC, daisukes commented
では、こんな感じにすれば

https://github.com/CMU-cabot/cabot-ios-app/blob/9eabdcb435811bb81000bd52d967926b4c800d95/CaBot/CaBotAppModel.swift#L1010

2024-05-20 11:53 UTC, miyazakifuki commented
ありがとうございます。修正しました。

2024-05-20 13:56 UTC, daisukes commented
修正ありがとうございます。今後翻訳作業があるので、なるべく標準のものを使いたいです。

日付部分はここにあるように標準のものを使いませんか？
https://developer.apple.com/documentation/foundation/dateformatter#1680045

```
let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium    // .long .medium .short .none
dateFormatter.timeStyle = .none      // .long .medium .short .none
 
let date = Date(timeIntervalSinceReferenceDate: 118800)
 
// US English Locale (en_US)
dateFormatter.locale = Locale(identifier: "en_US")
```

2024-05-21 01:38 UTC, miyazakifuki commented
あ、すみません。日付部分というのを見逃して時間の部分も標準化させてしまいました。
時間が1分以内だと変な表示になってしまうようなのですが、ケースとして無視するのか時間の部分は一つ前の形に戻すかどちらの方が良さそうでしょうか？

![IMG_0154](https://github.com/CMU-cabot/cabot-ios-app/assets/101164062/cf17cdfe-3138-4052-b478-587546d84485)

2024-05-21 02:50 UTC, daisukes commented
```
            timeFormatter.timeStyle = .medium
```

として`HH:mm:ss`のフォーマットにしてしまうのはどうでしょうか？
`HH時mm分`のフォーマットにこだわらなくても良いかなぁという気がします。
（そもそも時間差分が1分以内の時のフォーマットがおかしいのが原因ですが。。。）

<img src="https://github.com/CMU-cabot/cabot-ios-app/assets/43101027/075b886f-e32e-4bfd-adda-a5a915dabcaf" width="480"/>

2024-05-21 05:35 UTC, miyazakifuki commented
1分未満は1分として扱う方針で実装しました。
いらなくなった文言も消しました。

2024-05-21 10:44 UTC, dsato80 approved these changes
LGTM

2024-05-21 10:44 UTC, merged